// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductCatalog.Repository;

namespace ProductCatalog.Repository.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20200426065428_updated-data")]
    partial class updateddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductCatalog.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Baby Orange - Training Teether Tooth Brush for Infant, Baby, and Toddler",
                            Name = "Teether"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Pacifier Value Pack, Boy, 6-18 Months (Pack of 3)",
                            Name = "Foo Pacifier value pack"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fisher-Price Fidget Cube",
                            Name = "Baby fidget cube"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Costco steps walker (12 - 18 months)",
                            Name = "Steps Walker"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Activity floor seat and booster all in one",
                            Name = "Summer Booster chair"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Bassinet - 1 to 8 months",
                            Name = "Bassinet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
