Write-Host "Creating identity server"
dotnet ef migrations add InitialIdentityServerConfigurationDBMigration --context ConfigurationDbContext --startup-project "Registry.IDP"
dotnet ef migrations add InitialIdentityServerOperationalMigration --context PersistedgrantDbContext --startup-project "Registry.IDP"
Write-Host "Creating product catalog."
dotnet ef database update  --startup-project "ProductCatalog.Api"
Write-Host "Creating reviews."
dotnet ef database update  --startup-project "Reviews.Api"
Write-Host "Creating Registry."
dotnet ef database update  --startup-project "Registry.UI"
Write-Host "Successfully created and initialized databases."